name: test
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
        - escapace.aws_cloudwatch
        - escapace.docker
        - escapace.dotfiles
        - escapace.dummy
        - escapace.duo_unix
        - escapace.epel
        - escapace.ferm
        - escapace.kresd
        - escapace.storage_setup
        # - escapace.normalize
        - escapace.ntp
        - escapace.ssh
        - escapace.sudo
        - escapace.swap
        # - escapace.tor
        - escapace.tuned
        # - escapace.tunnelbroker
        - escapace.unattended_upgrades
        # - escapace.virtualbox
        # - escapace.wireguard
    steps:
    - name: docker login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v2.1.7
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: setup python environment
      uses: actions/setup-python@v2.3.0
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: install requirements
      run: |
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        ansible-galaxy collection install ansible.netcommon --upgrade
    - name: run molecule test
      run: |
        molecule --version
        python3 --version
        export ANSIBLE_ROLES_PATH="$(readlink -f "./roles")"
        cd roles/${{ matrix.role }}
        molecule test
