name: test
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
        - escapace.aws_cli
        - escapace.cloudflared
        - escapace.cni
        - escapace.consul
        - escapace.docker
        - escapace.dotfiles
        - escapace.dummy
        - escapace.duo_unix
        - escapace.envoy
        - escapace.epel
        - escapace.escapace_releases
        - escapace.ferm
        - escapace.gomplate
        - escapace.kresd
        - escapace.newrelic
        - escapace.nomad
        - escapace.ntp
        - escapace.observability
        - escapace.ssh
        - escapace.storage_setup
        - escapace.sudo
        - escapace.swap
        - escapace.tailscale
        - escapace.tuned
        - escapace.unattended_upgrades
        - escapace.vault
        # - escapace.aws_cloudwatch
        # - escapace.datadog
        # - escapace.normalize
        # - escapace.tor
        # - escapace.tunnelbroker
        # - escapace.virtualbox
        # - escapace.wireguard
    steps:
    - name: docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v3.3.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: setup python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: install requirements
      run: |
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        ansible-galaxy collection install -r requirements.yml --upgrade
    - name: run molecule test
      run: |
        molecule --version
        python3 --version
        export ANSIBLE_ROLES_PATH="$(readlink -f "./roles")"
        cd roles/${{ matrix.role }}
        molecule test
